# Generated by Django 2.0.5 on 2018-05-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paste',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='paste',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='paste',
            name='name',
        ),
        migrations.AlterField(
            model_name='paste',
            name='language',
            field=models.CharField(choices=[('python', 'python'), ('javascript', 'javascript'), ('outros', 'outros')], default='python', max_length=100),
        ),
        migrations.AlterField(
            model_name='paste',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
